declare module 'vue-dom-lazy-load';
declare module 'vue-html5-editor';
declare module 'vue-images-lazy-load';
declare module 'vue-lazy-store';
declare module 'vue-rescroll';
declare module 'js-cookie';
declare module '*.js';
declare module 'vue-audios';
declare module 'vue-virtual-scroll-list';
